[build]
  base = "html.anasimarketing.ltd/2025/anasimarketing-html"
  publish = "."

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/about"
  to = "/page-about.html"
  status = 200
  force = true
